apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: ${APP_NAME}
  name: ${APP_NAME}
  namespace: dev-${APP_NAME}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      component: ${APP_NAME}
  template:
    metadata:
      labels:
        component: ${APP_NAME}
    spec:
      containers:
        - env:
            - name: CACHE_IGNORE
              value: js|html
            - name: CACHE_PUBLIC_EXPIRATION
              value: 3d
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BRANCH_NAME-${GIT_HASH}-$BUILD_NUMBER
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
